Hack to get native 0.2-SNAPSHOT linking.
```
scala.NotImplementedError: an implementation is missing
    at java.lang.Throwable::init_java.lang.String_java.lang.Throwable
    at java.lang.Error::init_java.lang.String_java.lang.Throwable
    at java.lang.Error::init_java.lang.String
    at scala.NotImplementedError::init_java.lang.String
    at scala.NotImplementedError::init
    at scala.Predef$::???_nothing
    at java.lang.Class::isAssignableFrom_java.lang.Class_bool
    at scala.meta.internal.tokens.TokenInfo$class$::apply_scala.meta.internal.tokens.TokenInfo_scala.meta.tokens.Token_bool
    at scala.meta.internal.parsers.ScalametaParser$$anon$1::apply_scala.meta.tokens.Token_bool
    at scala.meta.internal.parsers.ScalametaParser$$anon$1::apply_java.lang.Object_bool
    at scala.meta.classifiers.Api$XtensionClassifiable::is_scala.meta.classifiers.Classifier_bool
    at scala.meta.internal.parsers.ScalametaParser::accept_scala.meta.internal.tokens.TokenInfo_unit
    at scala.meta.internal.parsers.ScalametaParser::parseRule_scala.Function1_scala.meta.Tree
    at scala.meta.internal.parsers.ScalametaParser::parseSource_scala.meta.Source
    at scala.meta.parsers.Parse$$anonfun$parseSource$1::apply_scala.meta.internal.parsers.ScalametaParser_scala.meta.Source
    at scala.meta.parsers.Parse$$anonfun$parseSource$1::apply_java.lang.Object_java.lang.Object
    at scala.meta.internal.parsers.ScalametaParser$$anon$202::apply_scala.meta.inputs.Input_scala.meta.Dialect_scala.meta.parsers.Parsed
    at scala.meta.parsers.Api$XtensionParseDialectInput::parse_scala.meta.parsers.Parse_scala.meta.parsers.Parsed
    at scala.meta.example.NativeMain$::main_scala.scalanative.runtime.ObjectArray_unit
    at main

java.lang.ArrayStoreException: Invalid array copy.
    at java.lang.Throwable::init_java.lang.String_java.lang.Throwable
    at java.lang.Exception::init_java.lang.String_java.lang.Throwable
    at java.lang.RuntimeException::init_java.lang.String_java.lang.Throwable
    at java.lang.RuntimeException::init_java.lang.String
    at java.lang.ArrayStoreException::init_java.lang.String
    at scala.scalanative.runtime.Array$::copy_scala.scalanative.runtime.Array_i32_scala.scalanative.runtime.Array_i32_i32_unit
    at scala.scalanative.runtime.Array$::copy_java.lang.Object_i32_java.lang.Object_i32_i32_unit
    at java.lang.System$::arraycopy_java.lang.Object_i32_java.lang.Object_i32_i32_unit
    at scala.compat.Platform$::arraycopy_java.lang.Object_i32_java.lang.Object_i32_i32_unit
    at scala.Array$::copy_java.lang.Object_i32_java.lang.Object_i32_i32_unit
    at scala.collection.mutable.ResizableArray$class$::copyToArray_scala.collection.mutable.ResizableArray_java.lang.Object_i32_i32_unit
    at scala.collection.mutable.ArrayBuffer::copyToArray_java.lang.Object_i32_i32_unit
    at scala.collection.TraversableOnce$class$::copyToArray_scala.collection.TraversableOnce_java.lang.Object_i32_unit
    at scala.collection.AbstractTraversable::copyToArray_java.lang.Object_i32_unit
    at scala.collection.TraversableOnce$class$::toArray_scala.collection.TraversableOnce_scala.reflect.ClassTag_java.lang.Object
    at scala.collection.AbstractTraversable::toArray_scala.reflect.ClassTag_java.lang.Object
    at scala.meta.internal.inputs.InternalInput$class$::scala$meta$internal$inputs$InternalInput$$cachedLineIndices_scala.meta.inputs.Input_scala.scalanative.runtime.IntArray
    at scala.meta.inputs.Input$File::scala$meta$internal$inputs$InternalInput$$cachedLineIndices$lzycompute_scala.scalanative.runtime.IntArray
    at scala.meta.inputs.Input$File::scala$meta$internal$inputs$InternalInput$$cachedLineIndices_scala.scalanative.runtime.IntArray
    at scala.meta.internal.inputs.InternalInput$class$::offsetToLine_scala.meta.inputs.Input_i32_i32
    at scala.meta.inputs.Input$File::offsetToLine_i32_i32
```